OkunaOrg/okuna-app

lib/widgets/post/post.dart

@uiboy I'll remove it for now so we can release

:fire: remove temporarilly fixed post height

---

lib/pages/home/pages/post_comments/post_comments_linked.dart

Fix post comments loading screen positioning

:bug: fix loading screen post commenters indicator position

---

lib/pages/home/pages/menu/pages/connections_circle/connections_circle.dart

https://openbookorg.slack.com/archives/CH0TAUFMH/p1553805906022400

🐛 Hide "Edit" link for "Connections" circle

---

lib/pages/home/modals/save_community.dart

Fixes #94.
Surely it can't be this easy? There must be something else I've missed, right!? 🤔

🐛 Fixed avatar and cover not saved when creating a community

---

lib/pages/home/pages/post_comments/widgets/post-commenter.dart

Another font fallback to fix missing text on some desktop platforms

🐛 Fix missing font fallback

---

android/app/src/main/AndroidManifest.xml
android/app/src/main/java/com/example/openbook/MainActivity.java
lib/pages/home/home.dart
lib/pages/home/modals/create_post/create_post.dart
lib/plugins/share/receive_share_state.dart
lib/plugins/share/share.dart
lib/services/modal_service.dart

This implements image sharing and fixes issue #166. Currently still a WIP as the actual post creation isn't yet implemented.

Share images from other apps directly to Openbook

---

lib/pages/home/home.dart

:bug: fix android back button not closing photo modal

---

lib/widgets/theming/smart_text.dart

This PR adjusts the regexes and the parsing used in smart text to find better username and community mentions.

🐛 Correctly mark mentions in words

---

android/app/src/main/AndroidManifest.xml
android/app/src/main/java/com/example/openbook/MainActivity.java
lib/pages/home/home.dart
lib/pages/home/modals/create_post/create_post.dart
lib/plugins/share/receive_share_state.dart
lib/plugins/share/share.dart
lib/services/modal_service.dart

This PR adds sharing text and links directly to Openbook on Android.

Sharing text and links

---

lib/pages/home/pages/profile/profile.dart

Fixes https://github.com/OpenbookOrg/openbook-api/issues/182

:bug: fix only 10 posts shown in profile

---

lib/models/badges_list.dart
lib/models/user_profile.dart

Fixes https://github.com/OpenbookOrg/openbook-app/issues/97

:bug: fix badges not shown sometimes

---

ios/Podfile.lock
ios/Runner.xcodeproj/project.pbxproj
lib/widgets/buttons/button.dart
lib/widgets/post/widgets/post-actions/widgets/post_action_react.dart

Show visual feedback when hitting unreact.

:sparkles: add visual feedback to unreact

---

lib/pages/home/bottom_sheets/post_actions.dart

API doesnt allow it, but this PR removes the edit post options for community admins on the app

:bug: do not show edit for admins

---

lib/pages/home/pages/menu/pages/useful_links.dart

New URL of community guide is: https://openbook.support/

:speech_balloon: updating url to community guide

---

lib/pages/home/pages/menu/pages/user_invites/user_invites.dart

:sparkles: Adjust Invites call to action

---

lib/pages/home/pages/menu/pages/delete_account/pages/confirm_delete_account.dart

Fixed typo.
"undoed" should be "undone"

✏️ Update confirm_delete_account.dart

---

README.md
assets/lang/en.json
assets/lang/es.json
lib/models/user_invite.dart
lib/pages/home/modals/accept_guidelines/pages/confirm_reject_guidelines.dart
lib/pages/home/pages/menu/menu.dart
lib/pages/home/pages/menu/pages/useful_links.dart
lib/pages/home/pages/moderated_objects/widgets/moderated_object/moderated_object.dart
lib/pages/home/pages/report_object/pages/confirm_report_object.dart

Manually went through and made updates, also left some links as is (Canny, Github, openbook.support) as the links themselves don't exist yet (including http://openspace.support/).
I did not modify any internal instances.

Changed instances of "Openbook" with "Openspace"

---

lib/pages/home/pages/menu/pages/useful_links.dart

openbook.canny.io -> okuna.canny.io
might have already been fixed in someone's branch but here it is anyway

🐛 fix canny URL

---

lib/services/storage.dart

Found a couple of issues in `_SecureStore` and `_SystemPreferencesStorage`:
- `set()` cached the _value_ into `_storedKeys`, instead of the key. 🤦‍♀️
This caused `clear()` to do nothing, since none of the "keys" would ever exist in the storage.
- `_storedKeys` contained only the keys for values that had been stored since the app was launched.
If you, for example, changed the comment order and then restarted the app, `clear()` would no longer clear this setting.
**Changes in this PR**
- `_SecureStore` now puts the key into `_storedKeys` instead of the value.
- `_SecureStore` now saves `_storedKeys` to SharedPreferences and restores it on app launch.
- `_SystemPreferencesStorage` clears all keys that are prefixed with `namespace.` when `clear()` is called. There is no need to manually keep …

🐛 Fix clearing preferences and secure storage doing nothing

---

lib/libs/pretty_count.dart
lib/widgets/post/post.dart

:bug: fix member counts

---

assets/i18n/en/drawer.arb
lib/pages/home/pages/menu/menu.dart
lib/pages/home/pages/menu/pages/about.dart
lib/services/localization.dart
lib/services/navigation_service.dart
lib/widgets/icon.dart
pubspec.lock
pubspec.yaml

This PR adds an about page to the app. The page displays app name, app version and platform version inside the app itself.

Add about page

---

lib/widgets/posts_stream/posts_stream.dart

This seems to be the culprit https://api.dartlang.org/stable/2.2.0/dart-core/Iterable/last.html

:bug: fix bad state no element

---

lib/models/user.dart
lib/services/localization.dart
lib/widgets/buttons/actions/follow_button.dart

Display Follow back when person is a follower instead of Follow.
This requires PR https://github.com/OkunaOrg/okuna-api/pull/604

:sparkles: add a follow back button when user is following and we're not

---

lib/pages/home/pages/timeline/timeline.dart

Fixes a white flash shown when opening the app and being in a dark theme

:bug: fix white flash on open app

---

lib/services/utils_service.dart

the `initializeDateFormatting` func is to be imported from a diff file, which does not cause the exception.

:bug: import function from a diff file in intl

---

lib/services/share.dart

Previously ShareService would first create a `CancelableOperation` around `_onShare()` and then create an entry in `_activeShares` for that operation. When sharing texts, `_onShare()` would run synchronously until it tried to use `_activeShares[share]`, which would crash with a null dereference.
Now we instead set up `_activeShares[share]` completely before calling `_onShare()`.

🐛 Fix text shares not working

---

lib/services/validation.dart
lib/widgets/theming/smart_text.dart

Fix the username RegEx on the app to validate and highlight the usernames correct.
Related to PR https://github.com/OkunaOrg/okuna-api/pull/717.
Thanks @Komposten who fixed my first draft. (https://github.com/OkunaOrg/okuna-api/issues/228)

:bug: Fix Username RegEx
