OkunaOrg/okuna-app

- lib/pages/home/pages/profile/widgets/profile_card/widgets/profile_actions/profile_actions.dart
Wraps the Edit profile button in a container with margin at the top and bottom. This fixes the Edit profile button being cut-off at the top, and makes the spacing consistent with the profile of another user.
The container and padding should be removed if your own profile also gets a `OBProfileActionMore` in the future.
Below a screenshot with the before and after.
> 🐛 Fix Edit profile button cutoff and make spacing consistent

- lib/pages/home/bottom_sheets/photo_picker.dart
- lib/pages/home/modals/edit_user_profile/edit_user_profile.dart
- lib/provider.dart
- lib/services/image_picker.dart
- lib/services/validation.dart
Fixes issue #170. `ImagePickerService` now throws an exception if the image is too large. The exception is caught by the widget that called the service, and an error toast is displayed.
Note: I wanted to access the image limit in the exception thrown by `ImagePickerService` so I added a getter in the `ValidationService` (used also by `ValidationService.isImageAllowedSize`) as a convenience method. This allows `ImagePickerService` to retrieve the limit and pass it to the exception constructor. Let me know if there is a better place (or way) for this.
> 🐛 Too large images are now rejected immediately

- lib/widgets/fields/text_form_field.dart
Longer error messages may not fit on one row on more narrow screens, so I changed `errorMaxLines` in OBTextFormField's TextFormField to default to 3 (to allow for slightly smaller screens, and maybe longer errors in other languages). See image below.
> 🐛 Fixed error messages not fitting on narrow screens

- lib/pages/home/pages/post_comments/widgets/post_comment/packages/post_comment_text.dart
- lib/widgets/post/widgets/post-body/widgets/post_body_text.dart
Kinda fixes issue #211. Doesn't allow text to be selected, but at least it can be copied. Long-press on the text in a post or comment will now copy the (full) text to the clipboard and show an info toast to notify the user.
One question: Do we want to add "Copy post text" to the post actions, or leave it as-is?
> ✨ Post and comment text can now be copied using long-press.

- lib/widgets/tiles/notification_tile/widgets/post_comment_notification_tile.dart
The notification tile for reactions also uses a `BoxFit.cover` which looks much better for most images.
> 🐛 Fix image preview being squashed in comment notification tile

- lib/pages/home/bottom_sheets/photo_picker.dart
- lib/pages/home/bottom_sheets/video_picker.dart
- lib/pages/home/modals/create_post/create_post.dart
- lib/pages/home/modals/create_post/widgets/create_post_text.dart
This adds some padding to the photo picker in order to "fix" the cutoff on iPhone X and newer. 
Like @lifenautjoe mentioned in #182 detecting specific phones isn't pretty, so the padding is applied for all devices. 
For the post actions bar/container (bar with yellow photo button) the padding is also applied to the top, so it also remains symmetrical on other devices.
> 🐛 Fix Photopicker cutoff on iPhone X and newer

- lib/pages/home/modals/zoomable_photo.dart
Inspired by @cyriana 's original PR on this issue 
The implementation now doesnt use the external dependancy, its fully custom, we listen to each pointer event using the `Listener` and calculate the velocity, direction etc of the swipe and then animate accordingly.
> :sparkles: make zoomable box dismissible in any direction with rotation

- lib/pages/auth/login.dart
- lib/pages/auth/reset_password/forgot_password_step.dart
Realised that I missed the login and reset password screens when I fixed this the first time...
> 🐛 Fixed some more error messages not fitting on narrow screens

- lib/widgets/http_list.dart
If the notification list is empty the tab doesn't contain a scroll view. This wasn't controlled for when tapping the notification icon (to refresh/scroll to top) so it tried to scroll to top anyway, causing an exception to occur (can't scroll a scroll view that doesn't exist).
> 🐛 Fixed exception when refreshing empty notification list

- lib/pages/home/pages/community/pages/community_members.dart
A user cannot follow itself, therefore removed follow button on members see/search
> :bug: remove follow button for own user

- lib/main.dart
- lib/plugins/desktop/error-reporting.dart
This PR adds the necessary platform override for running on desktop and a new error reporting plugin that's only used for the desktop app. This way, flutter errors can be logged a lot better.
> Better desktop integration

- lib/main.dart
Some text elements still don't show emojis. This PR adds the necessary font family fallback to the default text theme on desktop, for example to show emoji in markdown components.
> Font fallback on Desktop

- lib/services/httpie.dart
This PR changes the `HttpieService` to use a single `http.Client` for all requests and tries to find a proxy server from the environment.
A custom plugin will be needed to get proxy settings on platforms that don't set the `http_proxy` and `https_proxy` environment variables.
> ✨ Use same HttpClient for all requests

- lib/pages/home/modals/create_post/pages/share_post/pages/share_post_with_circles.dart
- lib/pages/home/modals/timeline_filters.dart
This is based on this Canny bug report: [Selecting Cycles and Connect - Logic error](https://okuna.canny.io/feature-requests/p/selecting-cycles-and-connect-logic-error).
What I've changed:
1) If you select the Connections circle when sharing a post, all other circles (except World) are auto-selected and disabled. This mirrors the behaviour of selecting the World circle.
2) If you select the Connections circle when filtering the timeline, all other circles are auto-selected and disabled.
3) Moved Connections to the top of the circle list in the timeline filter (to match the order they are in when sharing a post).
> 🐛 Selecting connections circle now disables other circles when sharing/filtering

- lib/models/notifications/notification.dart
- lib/models/push_notification.dart
- lib/pages/home/pages/notifications/notifications.dart
- lib/services/localization.dart
- lib/services/notifications_api.dart
- lib/services/user.dart
Fixes issue #249 by splitting the notification page into two tabs, one for general notifications and one for requests (currently connection requests and community invites).
This requires Okuna API PR #[305](https://github.com/OkunaOrg/okuna-api/pull/305) to function properly (without it all notifications are shown in both tabs).
> ✨ Split notifications into two tabs: General and Requests

- lib/pages/home/modals/create_post/create_post.dart
- lib/pages/home/pages/timeline/timeline.dart
- lib/services/localization.dart
- lib/widgets/buttons/community_floating_action_button.dart
- lib/widgets/icon.dart
Fixes Thommys recent complaints about screen reader not responding to "create new post" and close labels on many create/edit/save screens, fixed this so that it makes it way to the next release. 
We should do another comprehensive PR perhaps with an extensive accessibility review and provide more contextual labels on all our action buttons.
> :wheelchair: fix create new post and close labels

- make.bat
`make` does not exist as a command on Windows, and it cannot be installed and used without installing a Unix shell. As this is a hassle, I have Instead added `make.bat` which essentially emulates `make` and supports all options currently present in the `Makefile`.
If `Makefile` is updated in the future, we will also have to update `make.bat`.
Note: `make.bat` currently uses the new dart scripts from PR #378. If that PR is rejected, I'll update this one to use the original node commands.
> Makefile for windows

- lib/services/text_account_autocompletion.dart
Fixes #386.
The auto-completer tried to split on `' '` and then checked if the last string result started with `@`. This failed if the `@` was at the start of a line since it was then preceded by a new line rather than a normal space.
> 🐛 Fix mention suggestions not clickable after newline

- lib/pages/home/modals/create_post/create_post.dart
- lib/pages/home/modals/post_comment/post_comment_reply_expanded.dart
- lib/pages/home/modals/post_comment/post_commenter_expanded.dart
- lib/pages/home/pages/post_comments/widgets/post_commenter.dart
- lib/services/text_account_autocompletion.dart
Currently mention suggestions will only trigger if you write an @ at the very end of a post or comment input field. This PR enables the suggestion popup for mentions added _anywhere_ within the text.
**Example**
Write in a post or comment field:
> Hi,
> How are you?
Move the cursor between "Hi" and the comma, write a space and `@`, and suggestions should appear.
> Enable mention suggestions anywhere in the text

- lib/widgets/contextual_account_search_box.dart
Writing `@` and then erasing it before the suggestion list had loaded would eventually throw an exception. This happened because the suggestion list would finish loading and update its state after it had already been disposed.
Now `OBContextualAccountSearchBoxState` cancels the get and search operations before it is disposed.
> 🐛 Fix exception when closing loading suggestion list

- android/app/src/main/AndroidManifest.xml
- android/app/src/main/java/com/example/openbook/MainActivity.java
- assets/i18n/en/error.arb
- lib/pages/home/home.dart
- lib/pages/home/modals/save_post/create_post.dart
- lib/pages/home/pages/timeline/timeline.dart
- lib/plugins/share/share.dart
- lib/services/localization.dart
- lib/services/modal_service.dart
- lib/widgets/new_post_data_uploader.dart
Sharing text or images from another app will now trigger the same "create post flow" as when you create a post from the timeline. Additionally, if the user has navigated to another tab or page/route, they will be sent back to the timeline (at least they will be when the "switching tabs only works once" bug gets fixed). This only triggers if they actually create the post; cancelling the post modal will not change tab or pop any routes.
Issues to fix:
You can now share videos to Okuna on Android.
> Fix sharing + add video sharing

- lib/main.dart
- lib/plugins/proxy_settings.dart
- lib/provider.dart
- lib/services/httpie.dart
This PR automatically determines the proxy to use using the `ProxySettings` plugin. On mobile platforms, proxy configuration should be handled by flutter itself, so here the plugin just returns `null`. On desktop platforms this asks the embedder for the current proxy configuration.
The newly added `HttpieOverrides` class is set as an override for the main zone the app runs in. This way, all other plugins/libraries that use the `HttpClient` from `dart:http` will pick up on the proxy we've set.
> :sparkles: Add globally used proxy

- lib/services/link_preview.dart
This PR fixes link previews not appearing for URLs without path components. For example, `https://example.com` will currently not show a preview, but `https://example.com/` will.
Previously the full preview URL was passed to `getFileNameMimeType()`. This worked fine for URLs with paths (e.g. `https://example.com/path/to/file.png`). However, we get weird results for URLs without paths, like `https://example.com`. In this case it would look up a MIME type for ".com", and since the resulting MIME type is `application/ms...` (.com files are a type of executable on Windows) it ends up not displaying a preview.
With this PR we instead first extract the path component of the URL and then check for a MIME type in the path.
> 🐛 Fix some URLs (e.g. https://bandcamp.com) not getting previewed

- android/app/src/main/java/com/example/openbook/MainActivity.java
When a file is shared to Okuna we copy it into a temporary file before sending the share intent to Flutter. However, if the mediaCache directory didn't exist we failed to create the temporary file.
> 🐛 Fix sharing broken on Android

- lib/widgets/video_player/video_player.dart
This PR adds a missing check that the video widget is mounted before setting the state. Without this fix, `setState` throws an exception if the video has been unmounted while loading, for example when scrolling very fast through the app.
> Check for video widget state

- lib/pages/home/pages/community/community.dart
- lib/pages/home/pages/community/pages/community_staff/community_staff.dart
Tapping "Staff" on a private community you're not a member of will open an invisible staff page, which still captures gestures and must be dismissed before the app can be used again. This PR simply gives the empty staff page a background (or rather, gives it a non-zero width).
Note: It shouldn't be possible for a community to have both `community.administrators` and `community.moderators` set to null (that's another bug, possibly in the API). So this "empty staff page" situation shouldn't actually happen but in case it does it's better to have a blank page than an invisible one.
> 🐛 Fix invisible staff page for private communities

- assets/i18n/en/drawer.arb
- assets/i18n/en/post.arb
- assets/i18n/en/user.arb
- lib/pages/home/pages/menu/pages/useful_links.dart
- lib/services/localization.dart
- lib/widgets/icon.dart
Following the discussion on Slack from November 25th, I added a new link in the Useful links section of the app. The link is https://okuna.io/roadmap as suggested by @duichwer - so before merging this, a redirect has to be added to the webserver configuration. Also, I have not generated the changes to the i18n files as I do not have sufficient rights to upload something to Crowdin
> :globe_with_meridians: :bento: add link to Okuna roadmap in useful links

- lib/pages/auth/create_account/create_account.dart
- lib/pages/auth/create_account/email_step.dart
- lib/pages/auth/create_account/name_step.dart
- lib/pages/auth/create_account/password_step.dart
- lib/pages/auth/create_account/username_step.dart
- lib/pages/auth/create_account/widgets/auth_text_field.dart
- lib/pages/auth/login.dart
- lib/pages/auth/reset_password/forgot_password_step.dart
- lib/pages/auth/reset_password/set_new_password_step.dart
- lib/pages/auth/reset_password/verify_reset_password_link_step.dart
- lib/pages/waitlist/subscribe_email_step.dart
Since the first alpha version I've found it a little bit annoying that pressing 'enter' in the login form doesn't move focus from the username field to the password field; instead it just closes the keyboard.
Since I don't need to enter my log in information very often I didn't spend time fixing it. But, I came across a solution to this a couple of days ago when I was looking for something else so it felt like it was time. :slightly_smiling_face: 
**Changes in this PR**
Login page:
- Keyboard shows a "Next" button in the username field. Pressing it focuses on the password field.
- Keyboard shows an "Enter" button (same as before this PR) in the password field. Pressing it triggers a login (same as tapping Continue).
- Pressing "Enter" also works in the forgot password, password reset …
> Make 'enter' presses do something in the login/registration forms

- lib/pages/home/modals/save_post/create_post.dart
- lib/services/media.dart
- lib/services/share.dart
If a user opens a GIF keyboard and taps multiple GIFs in quick succession, all tapped GIFs would be added to the post. Now previous operations are cancelled for each new tap, so only the last tap will count.
> 🐛 Fix adding multiple GIFs to a post.

- lib/services/text_autocompletion.dart
After community auto completion the code tried to place the cursor 2 characters after the auto-completion. This meant that auto-completion at the end of a line would place the cursor after the last position in the line, which is invalid so Flutter treated it as 0.
Now we correctly place the the cursor only 1 character after the auto-completion.
I also reduced code duplication between the username, hashtag and community auto-completion methods.
> 🐛 Fix community auto-complete moves cursor to start of text
